org: auctus
app: dpiggy
service: dpiggy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  compoundRedeem:
    handler: handler.compoundRedeem
    timeout: 600
    reservedConcurrency: 1
    environment: ${ssm:/aws/reference/secretsmanager/dpiggy/lambda/${opt:stage, self:provider.stage}.env.json~true}
    events:
      - http:
          path: /compound
          method: post
          cors: true
      - schedule:
          rate: rate(30 minutes)
          enabled: true