org: auctus
app: dpiggy
service: dpiggy

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment: ${ssm:/aws/reference/secretsmanager/dpiggy/lambda/${opt:stage, self:provider.stage}.env.json~true}
  
functions:
  compoundRedeem:
    handler: handler.compoundRedeem
    timeout: 600
    reservedConcurrency: 1
    events:
      - http:
          path: /compound
          method: post
          cors: true
      - schedule:
          rate: rate(30 minutes)
          enabled: false
  check:
    handler: handler.check
    timeout: 900
    reservedConcurrency: 1
    events:
      - http:
          path: /compound/check
          method: post
          cors: true
  