export const faqData = [
    {id: 1, q:"What is dPiggy?", a:"dPiggy is a decentralized no-loss crypto investing platform, it allows users to gain exposure to crypto assets whilst protecting their principal invested."},
    {id: 2, q:"How does dPiggy work?", a:"Behind the scenes, the DAI deposited is supplied to the Compound protocol, where it generates interest. Every 30 days, dPiggy automatically purchases crypto on Uniswap from the interest earned."},
    {id: 3, q: "How do interest rate work? Can it change?", a: "Interest rate is determined algorithmically by the Compound protocol — expect it to change frequently based on supply and demand."},
    {id: 4, q:"How much does it cost?", a:"dPiggy has an annual fee of 0.10% per year on the amount invested — about $10 per year for every $10,000 invested. This fee is charged monthly and will never be above the interest generated during the month.\n\nAlternatively, you can lock 10,000 AUC and get 100% discount on fees."},
    {id: 5, q:"Has dPiggy been audited?", a:"dPiggy is currently in alpha and has not been audited yet - the codebase can be found on GitHub. Please don’t supply your life savings, or assets you can’t afford to lose. It should be considered experimental technology not for use with larger sums yet."},
    {id: 6, q:"Can I withdraw anytime?", a:"Yes, you can withdraw your assets any time."},
    {id: 7, q:"How is Auctus Inc. related to dPiggy?", a:"Auctus Inc. is the company that has built the dPiggy smart contracts and the dPiggy web application."},
    {id: 8, q:"What will the fee be used for?", a:"100% of fees generated with dPiggy will be used to buy & burn AUC tokens, the company responsible for dPiggy development."},
    {id: 9, q:"How can I get 100% discount on fees?", a:"Go to your dashboard, click on \"save fees\". You will be able to purchase 10,000 AUC (if you don't have on you wallet) and then lock this amount to stop paying fees.\n\nThese tokens can be returned to your wallet by clicking on \"withdraw all\" and terminating your dPiggy."}
]